#!/usr/bin/env python3
"""
Generates simple complex-shape OBJ files for asgn4.
Usage: python3 gen_models.py
Outputs:
  - torus_knot.obj : a (p,q)-torus knot tube, ~4000+ triangles, good for lighting.
"""
import math, os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))


def write_obj(path, verts, normals, faces):
    with open(path, "w") as f:
        f.write("# Generated by gen_models.py\n")
        for v in verts:
            f.write("v %.6f %.6f %.6f\n" % v)
        for n in normals:
            f.write("vn %.6f %.6f %.6f\n" % n)
        for a, b, c in faces:
            # 1-based; same index for vertex and normal
            f.write("f %d//%d %d//%d %d//%d\n" % (a, a, b, b, c, c))


def torus_knot(p=2, q=3, R=1.0, r=0.3, tubular=200, radial=24):
    """Generates a tube around a (p,q)-torus knot curve."""
    # Curve sampling
    curve = []
    tangents = []
    eps = 1e-3
    for i in range(tubular):
        t = (i / tubular) * 2.0 * math.pi
        x = (R + r * math.cos(q * t)) * math.cos(p * t)
        y = (R + r * math.cos(q * t)) * math.sin(p * t)
        z = r * math.sin(q * t)
        curve.append((x, y, z))
        # Approximate tangent
        t2 = t + eps
        x2 = (R + r * math.cos(q * t2)) * math.cos(p * t2)
        y2 = (R + r * math.cos(q * t2)) * math.sin(p * t2)
        z2 = r * math.sin(q * t2)
        tx, ty, tz = (x2 - x), (y2 - y), (z2 - z)
        L = math.sqrt(tx * tx + ty * ty + tz * tz) or 1.0
        tangents.append((tx / L, ty / L, tz / L))

    # Build a frame along each curve sample (parallel transport)
    normals_curve = []
    binormals_curve = []
    # Initial normal: pick any vector orthogonal to first tangent
    T0 = tangents[0]
    if abs(T0[0]) < 0.5:
        ref = (1.0, 0.0, 0.0)
    else:
        ref = (0.0, 1.0, 0.0)
    N0 = (T0[1] * ref[2] - T0[2] * ref[1],
          T0[2] * ref[0] - T0[0] * ref[2],
          T0[0] * ref[1] - T0[1] * ref[0])
    L = math.sqrt(sum(c * c for c in N0)) or 1.0
    N0 = (N0[0] / L, N0[1] / L, N0[2] / L)
    normals_curve.append(N0)

    for i in range(1, tubular):
        T = tangents[i]
        Nprev = normals_curve[-1]
        # Re-orthogonalize: project Nprev onto plane perpendicular to T
        d = T[0] * Nprev[0] + T[1] * Nprev[1] + T[2] * Nprev[2]
        N = (Nprev[0] - d * T[0], Nprev[1] - d * T[1], Nprev[2] - d * T[2])
        Ln = math.sqrt(sum(c * c for c in N)) or 1.0
        N = (N[0] / Ln, N[1] / Ln, N[2] / Ln)
        normals_curve.append(N)

    for i in range(tubular):
        T = tangents[i]
        N = normals_curve[i]
        B = (T[1] * N[2] - T[2] * N[1],
             T[2] * N[0] - T[0] * N[2],
             T[0] * N[1] - T[1] * N[0])
        binormals_curve.append(B)

    # Build vertex grid
    verts = []
    norms = []
    for i in range(tubular):
        C = curve[i]
        N = normals_curve[i]
        B = binormals_curve[i]
        for j in range(radial):
            a = (j / radial) * 2.0 * math.pi
            ca = math.cos(a)
            sa = math.sin(a)
            nx = N[0] * ca + B[0] * sa
            ny = N[1] * ca + B[1] * sa
            nz = N[2] * ca + B[2] * sa
            x = C[0] + r * 0.5 * nx
            y = C[1] + r * 0.5 * ny
            z = C[2] + r * 0.5 * nz
            verts.append((x, y, z))
            norms.append((nx, ny, nz))

    faces = []
    for i in range(tubular):
        i1 = (i + 1) % tubular
        for j in range(radial):
            j1 = (j + 1) % radial
            # Indices (1-based for OBJ)
            a = i  * radial + j  + 1
            b = i1 * radial + j  + 1
            c = i1 * radial + j1 + 1
            d = i  * radial + j1 + 1
            faces.append((a, b, c))
            faces.append((a, c, d))

    return verts, norms, faces


if __name__ == "__main__":
    v, n, f = torus_knot(p=2, q=3, R=1.0, r=0.4, tubular=256, radial=24)
    write_obj(os.path.join(OUT_DIR, "torus_knot.obj"), v, n, f)
    print("Wrote torus_knot.obj  verts=%d  faces=%d" % (len(v), len(f)))
